### ISSUE TITLE
Penambahan MVC 

### ISSUE THREAD

**Issue by 12200921** [12200921/sistem-informasi-sekolah#1]
- Views
- Controller
- Model

**Comment by DwiNurfitria** [comment]
sudah menambahka file view ke dalam folder views

**Comment by fitriindriyani** [comment]
telah menambahkan file Controllers dan Models

**Comment by aureliayolanda** [comment]
sudah menambahkan MIGRATIONS

**Comment by ListiaNingrum** [comment]
Sudah menambahkan auth dan view/template

**Comment by 12200921** [comment]
terima kasih
